apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: session-service
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: session-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: session-service
    spec:
      containers:
      - image: zoranashura402/session
        imagePullPolicy: IfNotPresent
        name: session-service
        envFrom:
          - configMapRef:
              name: session-config
          - configMapRef:
              name: general-config
          - secretRef:
              name: postgres-secret
        resources:
          requests:
            memory: "600Mi"
        command: ["java", "-jar", "/app/app.jar"]
        ports:
        - containerPort: 8081
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gateway-service
    spec:
      containers:
      - image: zoranashura402/gateway
        imagePullPolicy: IfNotPresent
        name: gateway-service
        envFrom:
          - configMapRef:
              name: services-ports
        command: ["java", "-jar", "/app/app.jar"]
        ports:
        - containerPort: 8087
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: loyalty-service
  name: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: loyalty-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: loyalty-service
    spec:
      containers:
      - image: zoranashura402/loyalty-service
        imagePullPolicy: IfNotPresent
        name: loyalty-service
        envFrom:
          - configMapRef:
              name: general-config
          - configMapRef:
              name: loyalty-config
          - secretRef:
              name: postgres-secret
        command: ["java", "-jar", "/app/app.jar"]
        ports:
        - containerPort: 8085
